import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import "bootstrap/dist/css/bootstrap.css"
import Gallery from '../components/Gallery'

export default function Home() {
  return (
    <div className='bg-dark'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center text-light py-4 mb-5">Image Gallery</h1>
      <Gallery/>
    </div>
  )
}
